
/* MotoCoder_Callbacks.h */
/* Generated by MotoCoder */
/* Version: 0.12.4 */
/* At: 2022-11-22 13:57:05 */
/* Copyright: 2022 Woodward. */


#ifndef MOTOCODER_CALLBACKS_H
#define MOTOCODER_CALLBACKS_H



#include <MotoCoder_Types.h>
	
/* Run-Time options, implemented as callbacks into the application */
extern void mh_CAN_1_CityID_Update(uint8_T *CAN_1_CityID);
extern void mh_CAN_2_CityID_Update(uint8_T *CAN_2_CityID);


#endif

