
/* MotoCoder_ModuleSupport_CAN.h */
/* Generated by MotoCoder */
/* Version: 0.12.4 */
/* At: 2022-11-22 13:57:05 */
/* Copyright: 2022 Woodward. */


#ifndef MOTOCODER_MODULESUPPORT_CAN_H
#define MOTOCODER_MODULESUPPORT_CAN_H



	
/* MotoCoder_ModuleSupport_CAN */
extern void ModuleSupport_KeySuiteSupport_CloseNonProgrammingCANLinks(uint8_T in_u8AllowConnectOnCANMask);

#endif

