
/* MotoCoder_Types.h */
/* Generated by MotoCoder */
/* Version: 0.12.4 */
/* At: 2019-01-01 09:49:19 */
/* Copyright: 2019 Woodward. */


#ifndef MOTOCODER_TYPES_H
#define MOTOCODER_TYPES_H



	


/* reference_T used as a pointer to DataStorage */
#ifndef defined_reference_T
#define defined_reference_T
typedef void * reference_T;
#endif

/* struct_reference_T used as a pointer to Structure DataStorage */
#ifndef defined_struct_reference_T
#define defined_struct_reference_T
typedef void * struct_reference_T;
#endif

#ifndef defined_char_T
#define defined_char_T
typedef char                   char_T;
#endif

#ifndef defined_boolean_T
#define defined_boolean_T
typedef unsigned char          boolean_T;
#endif

#ifndef defined_int8_T
#define defined_int8_T
typedef signed char            int8_T;
#endif

#ifndef defined_uint8_T
#define defined_uint8_T
typedef unsigned char          uint8_T;
#endif

#ifndef defined_int16_T
#define defined_int16_T
typedef short                  int16_T;
#endif

#ifndef defined_uint16_T
#define defined_uint16_T
typedef unsigned short         uint16_T;
#endif

#ifndef defined_int32_T
#define defined_int32_T
typedef int                    int32_T;
#endif

#ifndef defined_uint32_T
#define defined_uint32_T
typedef unsigned int           uint32_T;
#endif

#ifndef defined_int64_T
#define defined_int64_T
typedef long long              int64_T;
#endif

#ifndef defined_uint64_T
#define defined_uint64_T
typedef unsigned long long     uint64_T;
#endif

#ifndef defined_real32_T
#define defined_real32_T
typedef float                  real32_T;
#endif

#ifndef defined_real64_T
#define defined_real64_T
typedef double                 real64_T;
#endif

#define Interrupt_Disable() DISABLE()
#define Interrupt_Enable() UNDISABLE()
    /* S_ConstFault structure */
typedef struct {
    uint16_T   mode;
    uint16_T   id;
    uint16_T   test;
    uint16_T   xlim;
    uint16_T   ylim;
    uint16_T   action1;
    uint16_T   action1_condition;
    uint16_T   action2;
    uint16_T   action2_condition;
    uint16_T   action3;
    uint16_T   action3_condition;
    uint16_T   action4;
    uint16_T   action4_condition;
} S_ConstFault_T;

/* S_Fault structure */
typedef struct {
    uint16_T   x;
    uint16_T   y;
} S_Fault_T;

/* S_FaultAction structure */
typedef struct {
    uint8_T   reference_count;
} S_FaultAction_T;

/* S_FaultManager structure */
typedef struct {
    uint8_T   suspected[12];
    uint8_T   active[12];
    uint8_T   occurred[12];
    uint8_T   last_suspected_fault;
    uint8_T   last_unsuspected_fault;
    uint8_T   last_active_fault;
    uint8_T   last_inactive_fault;
    uint8_T   last_occurred_fault;
} S_FaultManager_T;

/* S_DispFaultManager structure */
typedef struct {
    uint8_T   current_suspected_vardec;
    uint8_T   current_active_vardec;
    uint8_T   current_occurred_vardec;
} S_DispFaultManager_T;

/* S_ConstFaultManager structure */
typedef struct {
    uint8_T   num_faults;
    uint16_T   num_actions;
} S_ConstFaultManager_T;

/* FaultActions Enumeration */
typedef enum {
    FAULTACTIONS_CUTTHROTTLE=0,
    FAULTACTIONS_DELAYEDENGINESHUTDOWN=1,
    FAULTACTIONS_OPENPARENNONECLOSEPAREN=10,
    FAULTACTIONS_DISABLEAC=2,
    FAULTACTIONS_DISABLECRUISE=3,
    FAULTACTIONS_DISABLEO2CTRL=4,
    FAULTACTIONS_DISABLEWASTEGATE=5,
    FAULTACTIONS_ENGINESHUTDOWN=6,
    FAULTACTIONS_HARDREVLIMIT=7,
    FAULTACTIONS_MEDIUMREVLIMIT=8,
    FAULTACTIONS_SOFTREVLIMIT=9,
} E_FaultActions;

/* FaultDisp Enumeration */
typedef enum {
    FAULTDISP_CURRENTSUSPECTED=0,
    FAULTDISP_CURRENTACTIVE=1,
    FAULTDISP_CURRENTOCCURRED=2,
} E_FaultDisp;

/* Fault_Cols Enumeration */
typedef enum {
    FAULT_COLS_MODE=0,
    FAULT_COLS_ID=1,
    FAULT_COLS_ACTION3CONDITION=10,
    FAULT_COLS_ACTION4=11,
    FAULT_COLS_ACTION4CONDITION=12,
    FAULT_COLS_TEST=2,
    FAULT_COLS_FAULTYSAMPLESOPENPARENXCLOSEPAREN=3,
    FAULT_COLS_TOTALSAMPLESOPENPARENYCLOSEPAREN=4,
    FAULT_COLS_ACTION1=5,
    FAULT_COLS_ACTION1CONDITION=6,
    FAULT_COLS_ACTION2=7,
    FAULT_COLS_ACTION2CONDITION=8,
    FAULT_COLS_ACTION3=9,
} E_Fault_Cols;

/* Fault_Command Enumeration */
typedef enum {
    FAULT_COMMAND_DASH=0,
    FAULT_COMMAND_CLEARALLFAULTS=1,
} E_Fault_Command;

/* Fault_Cond Enumeration */
typedef enum {
    FAULT_COND_OPENPARENNONECLOSEPAREN=0,
    FAULT_COND_SUSPECTED=1,
    FAULT_COND_ACTIVE=2,
    FAULT_COND_SUSPECTEDORACTIVE=3,
    FAULT_COND_OCCURRED=4,
    FAULT_COND_SUSPECTEDOROCCURRED=5,
    FAULT_COND_ACTIVEOROCCURRED=6,
    FAULT_COND_SUSPECTEDORACTIVEOROCCURRED=7,
} E_Fault_Cond;

/* Fault_Mode Enumeration */
typedef enum {
    FAULT_MODE_DISABLED=0,
    FAULT_MODE_ENABLED=1,
    FAULT_MODE_STICKY=2,
    FAULT_MODE_ENABLEDDASHPERSISTENT=3,
    FAULT_MODE_STICKYDASHPERSISTENT=4,
    FAULT_MODE_SAVEOCCURRED=5,
} E_Fault_Mode;

/* Fault_Test Enumeration */
typedef enum {
    FAULT_TEST_DASH=0,
    FAULT_TEST_TEST=1,
} E_Fault_Test;

/* Faults Enumeration */
typedef enum {
    FAULTS_ACCHARGEHIGH_FAULT=0,
    FAULTS_ACCHARGELOW_FAULT=1,
    FAULTS_CAMSYNCFAULT=10,
    FAULTS_CRANKEDGESFAULT=11,
    FAULTS_CRANKSYNCFAULT=12,
    FAULTS_CRUISEACCEL_FAULT=13,
    FAULTS_ECTOVERTEMPFAULT=14,
    FAULTS_ECTRANGEHIGH=15,
    FAULTS_ECTRANGELOW=16,
    FAULTS_ECTSEVEREOVERTEMPFAULT=17,
    FAULTS_EST1_OPEN=18,
    FAULTS_EST1_SHORT=19,
    FAULTS_ACPRESRANGEHIGH=2,
    FAULTS_EST2_OPEN=20,
    FAULTS_EST2_SHORT=21,
    FAULTS_EST3_OPEN=22,
    FAULTS_EST3_SHORT=23,
    FAULTS_EST4_OPEN=24,
    FAULTS_EST4_SHORT=25,
    FAULTS_EST5_OPEN=26,
    FAULTS_EST5_SHORT=27,
    FAULTS_EST6_OPEN=28,
    FAULTS_EST6_SHORT=29,
    FAULTS_ACPRESRANGELOW=3,
    FAULTS_EST7_OPEN=30,
    FAULTS_EST7_SHORT=31,
    FAULTS_EST8_OPEN=32,
    FAULTS_EST8_SHORT=33,
    FAULTS_ETCSPRINGTEST=34,
    FAULTS_ETC_OPEN_FAULT=35,
    FAULTS_ETC_STICKING=36,
    FAULTS_EVAPRANGEHIGH=37,
    FAULTS_EVAPRANGELOW=38,
    FAULTS_FUELADAPTRANGEHI=39,
    FAULTS_APP1RANGEHIGH=4,
    FAULTS_FUELADAPTRANGELOW=40,
    FAULTS_FUELPRESHIGH_FAULT=41,
    FAULTS_FUELPRESLOW_FAULT=42,
    FAULTS_FUELPRESRANGEHIGH=43,
    FAULTS_FUELPRESRANGELOW=44,
    FAULTS_FUELSENSRANGEHIGH=45,
    FAULTS_FUELSENSRANGELOW=46,
    FAULTS_HARDOVERBOOST_FAULT=47,
    FAULTS_HARDOVERSPEED=48,
    FAULTS_IATRANGEHIGH=49,
    FAULTS_APP1RANGELOW=5,
    FAULTS_IATRANGELOW=50,
    FAULTS_INJ1OPEN=51,
    FAULTS_INJ2OPEN=52,
    FAULTS_INJ3OPEN=53,
    FAULTS_INJ4OPEN=54,
    FAULTS_INJ5OPEN=55,
    FAULTS_INJ6OPEN=56,
    FAULTS_INJ7OPEN=57,
    FAULTS_INJ8OPEN=58,
    FAULTS_MAFRANGEHIGH=59,
    FAULTS_APP2RANGEHIGH=6,
    FAULTS_MAFRANGELOW=60,
    FAULTS_MAPRANGEHIGH=61,
    FAULTS_MAPRANGELOW=62,
    FAULTS_MAPTIMERANGEHIGH=63,
    FAULTS_MAPTIMERANGELOW=64,
    FAULTS_MAP_IR_HI=65,
    FAULTS_MAP_IR_LO=66,
    FAULTS_MAP_STICKING=67,
    FAULTS_MEDIUMOVERSPEED=68,
    FAULTS_NOOIL_FAULT=69,
    FAULTS_APP2RANGELOW=7,
    FAULTS_O2FAILEDLEAN=70,
    FAULTS_O2FAILEDRICH=71,
    FAULTS_O2NOTACTIVE=72,
    FAULTS_O2_POSTCATRANGEHIGH=73,
    FAULTS_O2_POSTCATRANGELOW=74,
    FAULTS_OILPRESRANGEHIGH=75,
    FAULTS_OILPRESRANGELOW=76,
    FAULTS_SENSVOLTRANGEHIGH=77,
    FAULTS_SENSVOLTRANGELOW=78,
    FAULTS_SOFTOVERBOOST_FAULT=79,
    FAULTS_APP_SENSORS_CONFLICT=8,
    FAULTS_SOFTOVERSPEED=80,
    FAULTS_SYSVOLTRANGEHIGH=81,
    FAULTS_SYSVOLTRANGELOW=82,
    FAULTS_TPS1RANGEHIGH=83,
    FAULTS_TPS1RANGELOW=84,
    FAULTS_TPS2RANGEHIGH=85,
    FAULTS_TPS2RANGELOW=86,
    FAULTS_TPS_SENSORS_CONFLICT=87,
    FAULTS_WASTEGATE_FAULT=88,
    FAULTS_OPENPARENNONECLOSEPAREN=89,
    FAULTS_CAMEDGESFAULT=9,
} E_Faults;

/* VarDecEnum_0 Enumeration */
typedef enum {
    VARDECENUM_0_PASSDASHTHROUGH=0,
    VARDECENUM_0_OVERRIDE=1,
} E_VarDecEnum_0;

/* VarDecEnum_1 Enumeration */
typedef enum {
    VARDECENUM_1_RUN=0,
    VARDECENUM_1_REBOOT=1,
} E_VarDecEnum_1;

/* VarDecEnum_13 Enumeration */
typedef enum {
    VARDECENUM_13_GOVENABLED=0,
    VARDECENUM_13_GOVDISABLED=1,
} E_VarDecEnum_13;

/* VarDecEnum_17 Enumeration */
typedef enum {
    VARDECENUM_17_EVAP_TEMP=0,
    VARDECENUM_17_PRESSURE=1,
} E_VarDecEnum_17;

/* VarDecEnum_18 Enumeration */
typedef enum {
    VARDECENUM_18_ETC=0,
    VARDECENUM_18_IAC=1,
} E_VarDecEnum_18;

/* VarDecEnum_19 Enumeration */
typedef enum {
    VARDECENUM_19_TOGGLE=0,
    VARDECENUM_19_HOLD=1,
} E_VarDecEnum_19;

/* VarDecEnum_2 Enumeration */
typedef enum {
    VARDECENUM_2_OFF=0,
    VARDECENUM_2_ON=1,
} E_VarDecEnum_2;

/* VarDecEnum_20 Enumeration */
typedef enum {
    VARDECENUM_20_TOGGLE=0,
    VARDECENUM_20_HOLD=1,
    VARDECENUM_20_NOT_USED=2,
} E_VarDecEnum_20;

/* VarDecEnum_21 Enumeration */
typedef enum {
    VARDECENUM_21_MULTIPLEXED=0,
    VARDECENUM_21_INDIVIDUAL_SWITCHES=1,
} E_VarDecEnum_21;

/* VarDecEnum_22 Enumeration */
typedef enum {
    VARDECENUM_22_2DASHWIRE=0,
    VARDECENUM_22_3DASHWIRE=1,
} E_VarDecEnum_22;

/* VarDecEnum_25 Enumeration */
typedef enum {
    VARDECENUM_25_RATELIMITER=0,
    VARDECENUM_25_LOWPASS=1,
    VARDECENUM_25_MOVINGAVERAGE=2,
} E_VarDecEnum_25;

/* VarDecEnum_26 Enumeration */
typedef enum {
    VARDECENUM_26_MODELFROMMAP=0,
    VARDECENUM_26_USEMAFSENSORDIRECTLY=1,
} E_VarDecEnum_26;

/* VarDecEnum_27 Enumeration */
typedef enum {
    VARDECENUM_27_ENABLE=0,
    VARDECENUM_27_CUT=1,
} E_VarDecEnum_27;

/* VarDecEnum_28 Enumeration */
typedef enum {
    VARDECENUM_28_CUTSPARK=0,
    VARDECENUM_28_CUTFUEL=1,
    VARDECENUM_28_CUTSPARKANDFUEL=2,
} E_VarDecEnum_28;

/* VarDecEnum_3 Enumeration */
typedef enum {
    VARDECENUM_3_DISABLED=0,
    VARDECENUM_3_ENABLED=1,
} E_VarDecEnum_3;

/* VarDecEnum_32 Enumeration */
typedef enum {
    VARDECENUM_32_DASH=0,
    VARDECENUM_32_STALL=1,
    VARDECENUM_32_CRANK=2,
    VARDECENUM_32_RUN=3,
} E_VarDecEnum_32;

/* VarDecEnum_36 Enumeration */
typedef enum {
    VARDECENUM_36_RISINGEDGE=0,
    VARDECENUM_36_FALLINGEDGE=1,
} E_VarDecEnum_36;

/* VarDecEnum_37 Enumeration */
typedef enum {
    VARDECENUM_37_WEAKPULLUP=0,
    VARDECENUM_37_STRONGPULLUP=1,
} E_VarDecEnum_37;

/* VarDecEnum_38 Enumeration */
typedef enum {
    VARDECENUM_38_OPENPARENNONECLOSEPAREN=-1,
    VARDECENUM_38_EST1=36,
    VARDECENUM_38_EST2=37,
    VARDECENUM_38_EST3=38,
    VARDECENUM_38_EST4=39,
    VARDECENUM_38_EST5=40,
    VARDECENUM_38_EST6=41,
    VARDECENUM_38_EST7=42,
    VARDECENUM_38_EST8=43,
} E_VarDecEnum_38;

/* VarDecEnum_39 Enumeration */
typedef enum {
    VARDECENUM_39_STANDARDOPENPARENCOILPERCYLINDERCLOSEPAREN=0,
    VARDECENUM_39_BANKEDOPENPARENFIREONBOTHPHASESUNTILCAMSYNCCLOSEPAREN=1,
    VARDECENUM_39_BATCHOPENPARENWASTEDSPARKCLOSEPAREN=2,
    VARDECENUM_39_MUXEDOPENPARENDISTRIBUTEDCLOSEPAREN=3,
} E_VarDecEnum_39;

/* VarDecEnum_4 Enumeration */
typedef enum {
    VARDECENUM_4_RUN=0,
    VARDECENUM_4_RESTORETODEFAULTS=1,
} E_VarDecEnum_4;

/* VarDecEnum_40 Enumeration */
typedef enum {
    VARDECENUM_40_OPENPARENNONECLOSEPAREN=-1,
    VARDECENUM_40_FINJ1=12,
    VARDECENUM_40_AINJ4=21,
    VARDECENUM_40_AINJ5=22,
    VARDECENUM_40_AINJ6=23,
    VARDECENUM_40_FINJ2=13,
    VARDECENUM_40_FINJ3=14,
    VARDECENUM_40_FINJ4=15,
    VARDECENUM_40_FINJ5=16,
    VARDECENUM_40_FINJ6=17,
    VARDECENUM_40_AINJ1=18,
    VARDECENUM_40_AINJ2=19,
    VARDECENUM_40_AINJ3=20,
} E_VarDecEnum_40;

/* VarDecEnum_41 Enumeration */
typedef enum {
    VARDECENUM_41_STANDARDOPENPARENINJECTORPERCYLINDERCLOSEPAREN=0,
    VARDECENUM_41_BATCHOPENPARENFIREHALFFUELONHALFOFTHEINJECTORSEVERYREVCLOSEPAREN=1,
    VARDECENUM_41_WASTEDOPENPARENFIREHALFFUELONALLINJECTORSEVERYREVCLOSEPAREN=2,
} E_VarDecEnum_41;

/* VarDecEnum_42 Enumeration */
typedef enum {
    VARDECENUM_42_STANDARD=0,
    VARDECENUM_42_TRANSIENT=1,
} E_VarDecEnum_42;

/* VarDecEnum_44 Enumeration */
typedef enum {
    VARDECENUM_44_CUTTHROTTLE=0,
    VARDECENUM_44_DELAYEDENGINESHUTDOWN=1,
    VARDECENUM_44_DISABLEAC=2,
    VARDECENUM_44_DISABLECRUISE=3,
    VARDECENUM_44_DISABLEO2CTRL=4,
    VARDECENUM_44_DISABLEWASTEGATE=5,
    VARDECENUM_44_ENGINESHUTDOWN=6,
    VARDECENUM_44_HARDREVLIMIT=7,
    VARDECENUM_44_MEDIUMREVLIMIT=8,
    VARDECENUM_44_SOFTREVLIMIT=9,
} E_VarDecEnum_44;

/* VarDecEnum_45 Enumeration */
typedef enum {
    VARDECENUM_45_DASH=0,
} E_VarDecEnum_45;

/* VarDecEnum_46 Enumeration */
typedef enum {
    VARDECENUM_46_OPENPARENNONECLOSEPAREN=-1,
    VARDECENUM_46_ECUP=53,
    VARDECENUM_46_AN7M=62,
    VARDECENUM_46_AN8M=63,
    VARDECENUM_46_AN9M=64,
    VARDECENUM_46_AN10M=65,
    VARDECENUM_46_AN11M=66,
    VARDECENUM_46_AN12M=67,
    VARDECENUM_46_AN13M=68,
    VARDECENUM_46_AN14M=69,
    VARDECENUM_46_AN15M=70,
    VARDECENUM_46_AN16M=71,
    VARDECENUM_46_DRVP=54,
    VARDECENUM_46_AN17M=72,
    VARDECENUM_46_AN18M=73,
    VARDECENUM_46_AN19M=74,
    VARDECENUM_46_O2A=90,
    VARDECENUM_46_O2B=91,
    VARDECENUM_46_XDRP_B=92,
    VARDECENUM_46_XDRP=55,
    VARDECENUM_46_AN1M=56,
    VARDECENUM_46_AN2M=57,
    VARDECENUM_46_AN3M=58,
    VARDECENUM_46_AN4M=59,
    VARDECENUM_46_AN5M=60,
    VARDECENUM_46_AN6M=61,
} E_VarDecEnum_46;

/* VarDecEnum_47 Enumeration */
typedef enum {
    VARDECENUM_47_5V=0,
    VARDECENUM_47_2POINT7V=1,
} E_VarDecEnum_47;

/* VarDecEnum_48 Enumeration */
typedef enum {
    VARDECENUM_48_OPENPARENNONECLOSEPAREN=-1,
    VARDECENUM_48_FUELP=0,
    VARDECENUM_48_FINJ3=14,
    VARDECENUM_48_FINJ4=15,
    VARDECENUM_48_FINJ5=16,
    VARDECENUM_48_FINJ6=17,
    VARDECENUM_48_AINJ1=18,
    VARDECENUM_48_AINJ2=19,
    VARDECENUM_48_AINJ3=20,
    VARDECENUM_48_AINJ4=21,
    VARDECENUM_48_AINJ5=22,
    VARDECENUM_48_AINJ6=23,
    VARDECENUM_48_HSOL1=2,
    VARDECENUM_48_TACH=24,
    VARDECENUM_48_EST1=36,
    VARDECENUM_48_EST2=37,
    VARDECENUM_48_EST3=38,
    VARDECENUM_48_EST4=39,
    VARDECENUM_48_EST5=40,
    VARDECENUM_48_EST6=41,
    VARDECENUM_48_EST7=42,
    VARDECENUM_48_EST8=43,
    VARDECENUM_48_MPRD=52,
    VARDECENUM_48_HSOL2=3,
    VARDECENUM_48_HSOL3=4,
    VARDECENUM_48_HSOL4=5,
    VARDECENUM_48_START=6,
    VARDECENUM_48_OILP=11,
    VARDECENUM_48_FINJ1=12,
    VARDECENUM_48_FINJ2=13,
} E_VarDecEnum_48;

/* VarDecEnum_49 Enumeration */
typedef enum {
    VARDECENUM_49_OPENPARENNONECLOSEPAREN=-1,
    VARDECENUM_49_DG1M=93,
    VARDECENUM_49_DG2M=94,
    VARDECENUM_49_DG4M=96,
    VARDECENUM_49_CNK=100,
} E_VarDecEnum_49;

/* VarDecEnum_5 Enumeration */
typedef enum {
    VARDECENUM_5_RUN=0,
    VARDECENUM_5_STORETOEEPROM=1,
} E_VarDecEnum_5;

/* VarDecEnum_50 Enumeration */
typedef enum {
    VARDECENUM_50_NOALIASPROTECT=0,
    VARDECENUM_50_USEALIASPROTECT=1,
} E_VarDecEnum_50;

/* VarDecEnum_51 Enumeration */
typedef enum {
    VARDECENUM_51_DIGITALINPUT=0,
    VARDECENUM_51_VRINPUT=1,
} E_VarDecEnum_51;

/* VarDecEnum_52 Enumeration */
typedef enum {
    VARDECENUM_52_OPENPARENNONECLOSEPAREN=-1,
    VARDECENUM_52_AN1M=56,
    VARDECENUM_52_AN10M=65,
    VARDECENUM_52_AN11M=66,
    VARDECENUM_52_AN12M=67,
    VARDECENUM_52_AN13M=68,
    VARDECENUM_52_AN14M=69,
    VARDECENUM_52_AN15M=70,
    VARDECENUM_52_AN16M=71,
    VARDECENUM_52_AN17M=72,
    VARDECENUM_52_AN18M=73,
    VARDECENUM_52_AN19M=74,
    VARDECENUM_52_AN2M=57,
    VARDECENUM_52_O2A=90,
    VARDECENUM_52_O2B=91,
    VARDECENUM_52_DG1M=93,
    VARDECENUM_52_DG2M=94,
    VARDECENUM_52_DG4M=96,
    VARDECENUM_52_ESTOP=97,
    VARDECENUM_52_AN3M=58,
    VARDECENUM_52_AN4M=59,
    VARDECENUM_52_AN5M=60,
    VARDECENUM_52_AN6M=61,
    VARDECENUM_52_AN7M=62,
    VARDECENUM_52_AN8M=63,
    VARDECENUM_52_AN9M=64,
} E_VarDecEnum_52;

/* VarDecEnum_53 Enumeration */
typedef enum {
    VARDECENUM_53_OPENPARENNONECLOSEPAREN=-1,
    VARDECENUM_53_FUELP=0,
    VARDECENUM_53_FINJ2=13,
    VARDECENUM_53_FINJ3=14,
    VARDECENUM_53_FINJ4=15,
    VARDECENUM_53_FINJ5=16,
    VARDECENUM_53_FINJ6=17,
    VARDECENUM_53_AINJ1=18,
    VARDECENUM_53_AINJ2=19,
    VARDECENUM_53_AINJ3=20,
    VARDECENUM_53_AINJ4=21,
    VARDECENUM_53_AINJ5=22,
    VARDECENUM_53_ETC=1,
    VARDECENUM_53_AINJ6=23,
    VARDECENUM_53_TACH=24,
    VARDECENUM_53_EST1=36,
    VARDECENUM_53_EST2=37,
    VARDECENUM_53_EST3=38,
    VARDECENUM_53_EST4=39,
    VARDECENUM_53_EST5=40,
    VARDECENUM_53_EST6=41,
    VARDECENUM_53_EST7=42,
    VARDECENUM_53_EST8=43,
    VARDECENUM_53_HSOL1=2,
    VARDECENUM_53_HSOL2=3,
    VARDECENUM_53_HSOL3=4,
    VARDECENUM_53_HSOL4=5,
    VARDECENUM_53_START=6,
    VARDECENUM_53_OILP=11,
    VARDECENUM_53_FINJ1=12,
} E_VarDecEnum_53;

/* VarDecEnum_6 Enumeration */
typedef enum {
    VARDECENUM_6_FALSE=0,
    VARDECENUM_6_TRUE=1,
} E_VarDecEnum_6;

/* VarDecEnum_7 Enumeration */
typedef enum {
    VARDECENUM_7_UNLOCKED=0,
    VARDECENUM_7_LOCKED=1,
} E_VarDecEnum_7;

/* VarDecEnum_8 Enumeration */
typedef enum {
    VARDECENUM_8_APP1=0,
    VARDECENUM_8_NORMAL=1,
} E_VarDecEnum_8;



#endif

